apiVersion: v1
kind: Secret
metadata:
  name: tourism-secrets
  labels:
    app: tourisminformation
type: Opaque
stringData:
  APP_JWT_SECRET: "9a2f8c7d6e5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f"
  DB_USERNAME: "sa"
  DB_PASSWORD: ""
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
